name: generate-esp-idf-vulnerabilities-pages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nvd-sync:
    name: Generate pages

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install esp-idf-sbom
        run: |
          pip install esp-idf-sbom

      - name: Generate web pages
        run: |
          python ./generate.py

      - name: Set up Git configuration
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git status
          git add .
          git commit -m "report $(date -u '+%Y-%m-%d %H:%M')"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
